version: '3.7'
services:
  deluge:
    container_name: deluge
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    image: deluge:stack
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/user/deluge/config:/deluge/config
      - /home/user/deluge/data:/deluge/downloads
